/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated/trips'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSubCategoriesRouteImport } from './routes/_authenticated/sub-categories'
import { Route as AuthenticatedReceiptsRouteImport } from './routes/_authenticated/receipts'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedTripsIndexRouteImport } from './routes/_authenticated/trips.index'
import { Route as AuthenticatedTripsTripIdRouteImport } from './routes/_authenticated/trips.$tripId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubCategoriesRoute =
  AuthenticatedSubCategoriesRouteImport.update({
    id: '/sub-categories',
    path: '/sub-categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceiptsRoute = AuthenticatedReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTripsIndexRoute = AuthenticatedTripsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTripsRoute,
} as any)
const AuthenticatedTripsTripIdRoute =
  AuthenticatedTripsTripIdRouteImport.update({
    id: '/$tripId',
    path: '/$tripId',
    getParentRoute: () => AuthenticatedTripsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/sub-categories': typeof AuthenticatedSubCategoriesRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/trips': typeof AuthenticatedTripsRouteWithChildren
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/trips/': typeof AuthenticatedTripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/sub-categories': typeof AuthenticatedSubCategoriesRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/trips': typeof AuthenticatedTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/receipts': typeof AuthenticatedReceiptsRoute
  '/_authenticated/sub-categories': typeof AuthenticatedSubCategoriesRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/trips': typeof AuthenticatedTripsRouteWithChildren
  '/_authenticated/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/_authenticated/trips/': typeof AuthenticatedTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categories'
    | '/dashboard'
    | '/export'
    | '/receipts'
    | '/sub-categories'
    | '/transactions'
    | '/trips'
    | '/trips/$tripId'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categories'
    | '/dashboard'
    | '/export'
    | '/receipts'
    | '/sub-categories'
    | '/transactions'
    | '/trips/$tripId'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/categories'
    | '/_authenticated/dashboard'
    | '/_authenticated/export'
    | '/_authenticated/receipts'
    | '/_authenticated/sub-categories'
    | '/_authenticated/transactions'
    | '/_authenticated/trips'
    | '/_authenticated/trips/$tripId'
    | '/_authenticated/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sub-categories': {
      id: '/_authenticated/sub-categories'
      path: '/sub-categories'
      fullPath: '/sub-categories'
      preLoaderRoute: typeof AuthenticatedSubCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipts': {
      id: '/_authenticated/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AuthenticatedReceiptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips/': {
      id: '/_authenticated/trips/'
      path: '/'
      fullPath: '/trips/'
      preLoaderRoute: typeof AuthenticatedTripsIndexRouteImport
      parentRoute: typeof AuthenticatedTripsRoute
    }
    '/_authenticated/trips/$tripId': {
      id: '/_authenticated/trips/$tripId'
      path: '/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AuthenticatedTripsTripIdRouteImport
      parentRoute: typeof AuthenticatedTripsRoute
    }
  }
}

interface AuthenticatedTripsRouteChildren {
  AuthenticatedTripsTripIdRoute: typeof AuthenticatedTripsTripIdRoute
  AuthenticatedTripsIndexRoute: typeof AuthenticatedTripsIndexRoute
}

const AuthenticatedTripsRouteChildren: AuthenticatedTripsRouteChildren = {
  AuthenticatedTripsTripIdRoute: AuthenticatedTripsTripIdRoute,
  AuthenticatedTripsIndexRoute: AuthenticatedTripsIndexRoute,
}

const AuthenticatedTripsRouteWithChildren =
  AuthenticatedTripsRoute._addFileChildren(AuthenticatedTripsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedReceiptsRoute: typeof AuthenticatedReceiptsRoute
  AuthenticatedSubCategoriesRoute: typeof AuthenticatedSubCategoriesRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedReceiptsRoute: AuthenticatedReceiptsRoute,
  AuthenticatedSubCategoriesRoute: AuthenticatedSubCategoriesRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedTripsRoute: AuthenticatedTripsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
